version: '3.8'

services:
  # Frontend service
  frontend:
    build:
      context: .
    ports:
      - "3003"
    environment:
      - NODE_ENV=production
      - PORT=3003
    restart: unless-stopped