version: '3.8'

services:
  # Frontend service
  frontend:
    build:
      context: .
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped 